[package]
name = "doseer_iced_ext"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
iced_core = { workspace = true }
iced_widget = { workspace = true, features = ["lazy"] }
