[package]
name = "doseer_fonts"
edition = { workspace = true }
version = "0.1.0"
authors = { workspace = true }
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
sleet_font_macro = { path = "./font_macro" }
